.\" Process this file with
.\" groff -man -Tascii bit2fp.1

.TH FPGATOOLS: "1" "September 2012"

.SH NAME
bit2fp \- bitstream to floorplan

.SH SYNOPSIS
.B bit2fp
.RB [--bit-header]
.RB [--bit-regs]
.RB [--no-model]
.RB [--no-fp-header]
.RB [--dump-routing-mips]
.RB <bitstream_file>

.SH AUTHORS
Wolfgang Spraul

.PP
This is free and unencumbered software released into the public domain.
for details see the UNLICENSE file at the root of the source tree.
